import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent { label 'principal' }
  environment {
    appName = "variable" 
  }
  stages {

 stage("paso 1"){
     
      steps {
          script {			
           "@echo off"
           "echo hola mundo"
        }
      }
    }
  }
  post {
      always {          
          deleteDir()
           "@echo off"
           "echo fase always"
      }
      success {
            "@echo off"
            "echo fase success"
        }

      failure {
            "@echo off"
            "echo fase failure"
      }
      
  }
}  

